stages:
  - lint
  - build

# Used for ci setup in the gitlab mirror of the project:
# https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines
variables:
  # Commit of ghc/ci-images repository from which to pull Docker images
  DOCKER_REV: "4ed1a4f27828ba96a34662dc954335e29b470cd2"

  CABAL_INSTALL_VERSION: 3.6.2.0

.windows_matrix: &windows_matrix
  matrix:
    - GHC_VERSION: 8.10.7
    - GHC_VERSION: 9.0.2
    - GHC_VERSION: 9.2.2
      ADD_CABAL_ARGS: "--ghc-options=-fcheck-prim-bounds -fno-ignore-asserts"

.darwin_matrix: &darwin_matrix
  matrix:
    - GHC_VERSION: 8.10.7
    - GHC_VERSION: 9.0.2
    - GHC_VERSION: 9.2.2
      ADD_CABAL_ARGS: "--ghc-options=-fcheck-prim-bounds -fno-ignore-asserts"

.m1_matrix: &m1_matrix
  matrix:
    - GHC_VERSION: 8.10.7
    - GHC_VERSION: 9.0.2
    - GHC_VERSION: 9.2.2
      ADD_CABAL_ARGS: "--ghc-options=-fcheck-prim-bounds -fno-ignore-asserts"

.linux_matrix: &linux_matrix
  matrix:
    - GHC_VERSION: 8.0.2
    - GHC_VERSION: 8.2.2
    - GHC_VERSION: 8.4.4
    - GHC_VERSION: 8.6.5
    - GHC_VERSION: 8.8.4
    - GHC_VERSION: 8.10.7
    - GHC_VERSION: 9.0.2
    - GHC_VERSION: 9.2.2
      ADD_CABAL_ARGS: "--ghc-options=-fcheck-prim-bounds -fno-ignore-asserts"

.artifacts:
  artifacts:
    expire_in: 2 week
    paths:
      - out

.artifacts:short:
  artifacts:
    expire_in: 1 day
    paths:
      - out

.build:
  extends: .artifacts:short
  stage: build
  script:
    - bash .gitlab/ci.sh

.aarch64-linux:
  tags:
    - aarch64-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/aarch64-linux-deb10:$DOCKER_REV"

.armv7-linux:
  tags:
    - armv7-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/armv7-linux-deb10:$DOCKER_REV"

.x86_64-linux-deb10:
  tags:
    - x86_64-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-deb10:$DOCKER_REV"

.x86_64-linux-deb9:
  tags:
    - x86_64-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-deb9:$DOCKER_REV"

.x86_64-linux-centos7:
  tags:
    - x86_64-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-centos7:$DOCKER_REV"

.x86_64-linux-fedora27:
  tags:
    - x86_64-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-fedora27:$DOCKER_REV"

.x86_64-linux-alpine:
  tags:
    - x86_64-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-alpine3_12:$DOCKER_REV"

.i386-linux-alpine:
  image: "registry.gitlab.haskell.org/ghc/ci-images/i386-linux-alpine3_12:$DOCKER_REV"
  tags:
    - x86_64-linux



######################
# i386 linux alpine
######################

build-i386-linux-alpine:
  extends:
    - .build
    - .i386-linux-alpine
  before_script:
    - sudo apk add --no-cache tar zlib zlib-dev zlib-static bzip2 bzip2-dev bzip2-static gmp gmp-dev xz xz-dev ncurses-static patchelf findutils tree


######################
# aarch64 linux deb10
######################

build-aarch64-linux-deb10:
  extends:
    - .build
    - .aarch64-linux
  before_script:
    - sudo apt update
    - sudo apt install -y patchelf tree


######################
# armv7 linux deb10
######################

build-armv7-linux-deb10:
  extends:
    - .build
    - .armv7-linux
  before_script:
    - sudo apt update
    - sudo apt install -y patchelf tree


######################
# x86_64 linux deb10
######################

build-x86_64-linux-deb10:
  extends:
    - .build
    - .x86_64-linux-deb10
  before_script:
    - sudo apt update
    - sudo apt install -y patchelf tree


######################
# x86_64 linux deb9
######################

build-x86_64-linux-deb9:
  extends:
    - .build
    - .x86_64-linux-deb9
  before_script:
    - sudo apt update
    - sudo apt install -y patchelf tree


######################
# x86_64 linux centos7
######################

build-x86_64-linux-centos7:
  extends:
    - .build
    - .x86_64-linux-centos7
  before_script:
    - sudo yum install -y epel-release
    - sudo yum install -y patchelf tree
  variables:
      ADD_CABAL_ARGS: "--constraint=text<2"


######################
# x86_64 linux fedora27
######################

build-x86_64-linux-fedora27:
  extends:
    - .build
    - .x86_64-linux-fedora27
  parallel: *linux_matrix
  before_script:
    - sudo dnf install -y patchelf tree


######################
# x86_64 linux alpine
######################

build-x86_64-linux-alpine:
  extends:
    - .build
    - .x86_64-linux-alpine
  before_script:
    - sudo apk add --no-cache tar zlib zlib-dev zlib-static bzip2 bzip2-dev bzip2-static gmp gmp-dev xz xz-dev ncurses-static patchelf findutils tree


######################
# x86_64 freebsd 12
######################

build-x86_64-freebsd12:
  extends: .build
  before_script:
    - sudo pkg update
    - sudo pkg install --yes patchelf gmake tree binutils
  tags:
    - x86_64-freebsd12
  allow_failure: true
  variables:
    ADD_CABAL_ARGS: "-j1"



######################
# x86_64 freebsd 13
######################

build-x86_64-freebsd13:
  extends: .build
  tags:
    - x86_64-freebsd13
  before_script:
    - sudo pkg update
    - sudo pkg install --yes compat12x-amd64 patchelf gmake tree binutils
  allow_failure: true
  variables:
    ADD_CABAL_ARGS: "-j1"


######################
# x86_64 darwin
######################

build-x86_64-darwin:
  extends: .build
  tags:
    - x86_64-darwin
  parallel: *darwin_matrix
  before_script:
    - /bin/bash ./.gitlab/brew.sh autoconf automake coreutils make tree
  # CPATH https://github.com/digital-asset/ghc-lib/issues/352
  script: |
    export PATH="$CI_PROJECT_DIR/.brew/bin:$CI_PROJECT_DIR/.brew/sbin:$PATH"
    export CPATH="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ffi:$CPATH"
    /bin/bash ./.gitlab/ci.sh
  after_script:
    - rm -Rf /private/tmp/.brew_tmp


######################
# aarch64 darwin
######################

build-aarch64-darwin:
  extends: .artifacts:short
  stage: build
  tags:
    - aarch64-darwin-m1
  parallel: *m1_matrix
  before_script:
    - export HOMEBREW_CHANGE_ARCH_TO_ARM=1
    - arch -arm64 /bin/bash ./.gitlab/brew.sh llvm autoconf automake coreutils make tree
  # C_INCLUDE_PATH: https://gitlab.haskell.org/ghc/ghc/-/issues/20592
  # CPATH https://github.com/digital-asset/ghc-lib/issues/352
  script: |
    export PATH="$CI_PROJECT_DIR/.brew/opt/llvm/bin:$CI_PROJECT_DIR/.brew/bin:$CI_PROJECT_DIR/.brew/sbin:$PATH"
    export CC=$CI_PROJECT_DIR/.brew/opt/llvm/bin/clang
    export CXX=$CI_PROJECT_DIR/.brew/opt/llvm/bin/clang++
    export LD=ld
    export AR=$CI_PROJECT_DIR/.brew/opt/llvm/bin/llvm-ar
    export RANLIB=$CI_PROJECT_DIR/.brew/opt/llvm/bin/llvm-ranlib
    export C_INCLUDE_PATH="`xcrun --show-sdk-path`/usr/include/ffi"
    export CPATH="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ffi:$CPATH"
    arch -arm64 /bin/bash ./.gitlab/ci.sh
  after_script:
    - rm -Rf /private/tmp/.brew_tmp
  variables:
    MACOSX_DEPLOYMENT_TARGET: "10.7"


######################
# x86_64 windows
######################

build-x86_64-windows:
  extends: .build
  tags:
    - new-x86_64-windows
  parallel: *windows_matrix
  script:
    - bash ./.gitlab/ci.sh
  retry: 2


######################
# hlint
######################

hlint:
  stage: lint
  extends:
    - .x86_64-linux-deb10
  script:
    - curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s -- -r System/
  allow_failure: true
  artifacts:
    expire_in: 2 week
    paths:
      - report.html
    when: on_failure

